name: testsAdd commentMore actions

on: 
  pull_request

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd auth && npm install --legacy-peer-deps && npm run test:ci
